### ISSUE TITLE
Cannot build this project (multidex)

### ISSUE THREAD

**Issue by samibel** [appodeal/appodeal-android-demo#12]
':app:transformClassesWithMultidexlistForDebug'.
> java.io.IOException: Can't write [//appodeal/app/build/intermediates/multi-dex/debug/componentClasses.jar] (Can't read [/Users/s/.gradle/caches/transforms-1/files-1.1/support-media-compat-25.2.0.aar/c6538d2c26a8d0a1db63477f19ab1f12/jars/classes.jar(;;;;;;**.class)] (Duplicate zip entry [classes.jar:android/support/v4/media/MediaMetadataCompat$TextKey.class]))

**Comment by BaxterZA** [comment]
Hi samibek! Thanks for the reply, i've updated build script.
