### ISSUE TITLE
Multidex infinite optimization

### ISSUE THREAD

**Issue by DimaDDM** [appodeal/appodeal-android-demo#15]
After enabling multidex for this library some devices trying optimize app on EVERY DEVICE BOOT. It's very annoying for users. It's possible to fix? Thanks.

**Comment by BaxterZA** [comment]
Hi @DimaDDM. How i can reproduce this problem?

**Comment by DimaDDM** [comment]
Hello. This issue occurs on some ART\ARM devices. It's cause multidex creating dex\odex files every time on boot device. Can you avoid using multidex? Non-dex build also too big for implementation without multidex :(

**Comment by BaxterZA** [comment]
Hi @DimaDDM! If you're not using MultiDex you can try max-dex sdk.

**Comment by DimaDDM** [comment]
max-dex too big for build. 64k limit exceeded even in a small project

**Comment by BaxterZA** [comment]
Closed this issue. If you still have questions please open a new one.
