### ISSUE TITLE
org.nexage.sourcekit.mraid.MRAIDView.destroy

### ISSUE THREAD

**Issue by askarsyzdykov** [appodeal/appodeal-android-demo#2]
With what may be due a mistake?

Device Huawei p6 u06
Android 4.2.2

> Fatal Exception: java.lang.IllegalArgumentException: Service not registered: android.speech.tts.TextToSpeech$Connection@41e7e348
>        at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:933)
>        at android.app.ContextImpl.unbindService(ContextImpl.java:1497)
>        at android.content.ContextWrapper.unbindService(ContextWrapper.java:484)
>        at android.speech.tts.TextToSpeech$Connection.disconnect(TextToSpeech.java:1321)
>        at android.speech.tts.TextToSpeech$1.run(TextToSpeech.java:661)
>        at android.speech.tts.TextToSpeech$1.run(TextToSpeech.java:656)
>        at android.speech.tts.TextToSpeech$Connection.runAction(TextToSpeech.java:1340)
>        at android.speech.tts.TextToSpeech.runAction(TextToSpeech.java:570)
>        at android.speech.tts.TextToSpeech.runActionNoReconnect(TextToSpeech.java:557)
>        at android.speech.tts.TextToSpeech.shutdown(TextToSpeech.java:656)
>        at android.webkit.AccessibilityInjector$TextToSpeechWrapper.shutdown(AccessibilityInjector.java:746)
>        at android.webkit.AccessibilityInjector.destroy(AccessibilityInjector.java:187)
>        at android.webkit.WebViewClassic.destroyJava(WebViewClassic.java:2688)
>        at android.webkit.WebViewClassic.destroy(WebViewClassic.java:2671)
>        at android.webkit.WebView.destroy(WebView.java:680)
>        at org.nexage.sourcekit.mraid.MRAIDView.destroy(Unknown Source)
>        at com.appodeal.ads.a.j.a(Unknown Source)
>        at com.appodeal.ads.f.a(Unknown Source)
>        at com.appodeal.ads.f.a(Unknown Source)
>        at com.appodeal.ads.f$1.onAnimationEnd(Unknown Source)
>        at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:973)
>        at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1012)
>        at android.animation.ValueAnimator.access$400(ValueAnimator.java:51)
>        at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:623)
>        at android.animation.ValueAnimator$AnimationHandler.run(ValueAnimator.java:639)
>        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
>        at android.view.Choreographer.doCallbacks(Choreographer.java:562)
>        at android.view.Choreographer.doFrame(Choreographer.java:531)
>        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
>        at android.os.Handler.handleCallback(Handler.java:725)
>        at android.os.Handler.dispatchMessage(Handler.java:92)
>        at android.os.Looper.loop(Looper.java:137)
>        at android.app.ActivityThread.main(ActivityThread.java:5095)
>        at java.lang.reflect.Method.invokeNative(Method.java)
>        at java.lang.reflect.Method.invoke(Method.java:511)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:665)
>        at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by BaxterZA** [comment]
Thank you, for your issue. We will fix this in next version of our sdk.

**Comment by BaxterZA** [comment]
Can you give more details? You using native android or framework?

**Comment by askarsyzdykov** [comment]
@BaxterZA native. 

minSdkVersion 15
targetSdkVersion 23
