### ISSUE TITLE
When we'll get the Xamarin package?

### ISSUE THREAD

**Issue by KirillVolkov** [appodeal/appodeal-android-demo#34]

**Comment by BaxterZA** [comment]
Hi @KirillVolkov! Thank you for your interest, but we don't have plan to create Xamarin plugin.

**Comment by KirillVolkov** [comment]
@BaxterZA Excuse me, but why? You had this plugin earlier

**Comment by sjkrypa** [comment]
@BaxterZA ok, but how can we use the Appodeal library in xamarin.android project? I cannot use jar binding project because of errors after building with the binded jar.
`Error: You have Jar libraries, resources.jar, resources.jar, resources.jar, that have the identical name with inconsistent file contents. Please make sure to remove any conflicting libraries in EmbeddedJar, InputJar and AndroidJavaLibrary.`

**Comment by KirillVolkov** [comment]
How we should to support your library in our xamarin projects? Play market removed our application with your old library

**Comment by KirillVolkov** [comment]
Ok, If you do not wont to create this plugin, please, if you can, help me to bind your jars
[https://github.com/KirillVolkov/AppodealXamarinPlugin_5.7.1](My Repo)
I built library, but if I plugin it into my project, I see these errors:
`/Users/kirillvolkov/Documents/dots/app/Droid/obj/Release/lp/1/jl/res/layout/mintegral_interstitial_activity.xml(0,0): Error APT0000: No resource found that matches the given name (at 'background' with value '@color/mintegral_interstitial_white'). (APT0000) (Points.Droid)`
`/Users/kirillvolkov/Documents/dots/app/Droid/obj/Release/lp/1/jl/res/layout/mintegral_reward_clickable_cta.xml(0,0): Error APT0000: No resource found that matches the given name (at 'background' with value '@color/mintegral_reward_cta_bg'). (APT0000) (Points.Droid)`
and other color and strings errors

**Comment by BaxterZA** [comment]
@KirillVolkov mintegral_interstitial_activity.xml and mintegral_reward_clickable_cta.xml are the resources and they available in the mintegral's aar files. 
Unfortunately we don't have resources to research these issues.

**Comment by KirillVolkov** [comment]
@BaxterZA thank you, but I built Xamarin library yesterday
[AppodealXamarinPlugin.dll.zip](https://github.com/appodeal/appodeal-android-demo/files/3555030/AppodealXamarinPlugin.dll.zip).
If somebody needs in this - you are welocome

**Comment by BaxterZA** [comment]
@KirillVolkov Thank you very much, let save the link here! I'll close the issue.
