### ISSUE TITLE
HELP appodeal developers! InterstitialActivity.finish () line

### ISSUE THREAD

**Issue by koljanich** [appodeal/appodeal-android-demo#4]
Hello Developers! I opened the source code of the appodeal.jar and found a very harmful line in the InterstitialActivities class. The onBackPressed method. The InterstitialActivity.finish () line! Users viewing ads do not even think about its content and just click the back button. If you remove this line, eCPM will grow tens of times! Users will at least look out of the corner of the eye and look for the exit button! If you do not delete this line, then at least add an exception method so that you can turn off the advertisement by clicking the Back on Unity framevork!

**Comment by BaxterZA** [comment]
Hello @koljanich ! Thanks for your question. But InterstitialActivities we use for showing MRAID advertisement, and by the MRAID spec, creative can hide native close button. And if we disable back button, and creative won't show close button, user can't close ads.

**Comment by koljanich** [comment]
How is this possible? Each ad has a Software close button! I looked through a lot of ads.

**Comment by BaxterZA** [comment]
You can look in spec https://www.iab.net/media/file/IAB_MRAID_v2_FINAL.pdf, useCustomClose method. And there are a lot of creatives with this behavior.

**Comment by koljanich** [comment]
I can not control the Activity of your library from the Unity. And I can not assemble SDK for a Unity without source code. Therefore, I ask to make a build for me without one line of code.

**Comment by BaxterZA** [comment]
I mean native close button, it's X button in top right corner, that i create in sdk. If ads  call useCustomClose method, i will hide my close button, and going to wait for close button from ads. But if ads won't create their close button and back button is disabled, user can't close ads. It's user protection. And others sdk has similar behavior.

**Comment by koljanich** [comment]
In 100% of cases I watched the close button on all interstitials. And besides, it's my problem that the user will not be able to close ads in my application. This they will write to me in the comments, not you. Why can not you make such a trifle?
