### ISSUE TITLE
Can't build Appodeal SDK 2.6

### ISSUE THREAD

**Issue by DimaDDM** [appodeal/appodeal-android-demo#45]
Hello. I can't build Appodeal SDK 2.6 for Android. Got this error
`ERROR: Manifest merger failed : Attribute application@fullBackupContent value=(false) from AndroidManifest.xml:45:9-42
	is also present at [com.vungle:publisher-sdk-android:6.4.11] AndroidManifest.xml:19:9-60 value=(@xml/vungle_backup_rule).
	Suggestion: add 'tools:replace="android:fullBackupContent"' to <application> element at AndroidManifest.xml:43:5-174:19 to override.`. Can you help me? Thank you.

**Comment by da2gl** [comment]
@DimaDDM Hi! Do you build a demo application? If not attach gradle file, please.

**Comment by DimaDDM** [comment]
> @DimaDDM Hi! Do you build a demo application? If not attach _build.gradle_ file, please.

Demo application building without problem, but my app - no. I'm trying different configurations but no one work.

First gradle file
https://pastebin.com/LzJTESLz
Second gradle file
https://pastebin.com/tKaR1s1y

**Comment by da2gl** [comment]
@DimaDDM Hi! Can you send android manifest file, please? Do you use `android:allowBackup ` and `android:fullBackupContent` in your application?

**Comment by DimaDDM** [comment]
I'm using 
```
android:fullBackupContent="false"
android:allowBackup="true"
```
in my manifest

**Comment by DimaDDM** [comment]
> @DimaDDM Hi! Can you send android manifest file, please? Do you use `android:allowBackup ` and `android:fullBackupContent` in your application?
> Your error contains describes one of the ways to solve the problem. You can also refuse of these settings, if they don't affect the logic of your app.

I'm using

```
android:fullBackupContent="false"
android:allowBackup="true"
```
in my manifest

**Comment by DimaDDM** [comment]
`tools:replace="android:allowBackup, android:fullBackupContent" `
Fixed by added in manifest
