### ISSUE TITLE
OutOfMemoryError chash

### ISSUE THREAD

**Issue by legd** [appodeal/appodeal-android-demo#6]
Hi guys, I'm having an issue with an OutOfMemoryError that is not related to my code, but I manage to identify that the error starts happening after upgrading the Appodeal SDK to the 2.0.2 version a few weeks ago, I read the change log of your newest version and it says you fixed some memory leaks, today I upgraded to the 2.1.3 version but I still have the problem,  any help with this bug? here is a portion of the error log:

09-12 15:56:28.034 6429-7091/com.bebler.app E/art: Throwing OutOfMemoryError "Failed to allocate a 960012 byte allocation with 383977 free bytes and 374KB until OOM"
09-12 15:56:28.276 6429-7091/com.bebler.app E/art: Throwing OutOfMemoryError "Failed to allocate a 960012 byte allocation with 383929 free bytes and 374KB until OOM"
09-12 15:56:48.130 6429-6429/com.bebler.app E/Base[onNativeFailedToLoad] - 347: ad failed to load
09-12 15:56:54.754 6429-7090/com.bebler.app E/art: Throwing OutOfMemoryError "Failed to allocate a 960012 byte allocation with 386537 free bytes and 377KB until OOM"
09-12 15:56:54.993 6429-7090/com.bebler.app E/art: Throwing OutOfMemoryError "Failed to allocate a 960012 byte allocation with 386409 free bytes and 377KB until OOM"

PD.: This error only occurs between 8:00 AM and 5:00 PM AST Time, not sure why.

**Comment by NikitaCherep** [comment]
Hi, may you send full stacktrack?

**Comment by legd** [comment]
Hi, this is a complete stacktrace, one thing I want to mention is this error happens with the app running but without any user interaction.

09-13 09:05:00.701 20376-20962/com.bebler.app E/art: Throwing OutOfMemoryError "Failed to allocate a 960012 byte allocation with 334957 free bytes and 327KB until OOM"
09-13 09:05:00.960 20376-20962/com.bebler.app E/art: Throwing OutOfMemoryError "Failed to allocate a 960012 byte allocation with 335165 free bytes and 327KB until OOM"
09-13 09:05:21.186 20376-20376/com.bebler.app E/Base[onNativeFailedToLoad] - 347: ad failed to load
09-13 09:05:27.197 20376-21262/com.bebler.app E/art: Throwing OutOfMemoryError "Failed to allocate a 960012 byte allocation with 318645 free bytes and 311KB until OOM"
09-13 09:05:27.436 20376-21262/com.bebler.app E/art: Throwing OutOfMemoryError "Failed to allocate a 960012 byte allocation with 318645 free bytes and 311KB until OOM"
09-13 09:05:58.237 20376-21263/com.bebler.app E/art: Throwing OutOfMemoryError "Failed to allocate a 960012 byte allocation with 318405 free bytes and 310KB until OOM"
09-13 09:05:58.472 20376-21263/com.bebler.app E/art: Throwing OutOfMemoryError "Failed to allocate a 960012 byte allocation with 318405 free bytes and 310KB until OOM"
09-13 09:06:39.183 20376-23719/com.bebler.app E/art: Throwing OutOfMemoryError "Failed to allocate a 960012 byte allocation with 317925 free bytes and 310KB until OOM"
09-13 09:06:39.443 20376-23719/com.bebler.app E/art: Throwing OutOfMemoryError "Failed to allocate a 960012 byte allocation with 317925 free bytes and 310KB until OOM"
09-13 09:07:40.600 20376-24360/com.bebler.app E/art: Throwing OutOfMemoryError "Failed to allocate a 960012 byte allocation with 316581 free bytes and 309KB until OOM"
09-13 09:07:40.844 20376-24360/com.bebler.app E/art: Throwing OutOfMemoryError "Failed to allocate a 960012 byte allocation with 316581 free bytes and 309KB until OOM"
09-13 09:08:31.934 20376-20376/com.bebler.app E/art: Throwing OutOfMemoryError "Failed to allocate a 3879468 byte allocation with 299340 free bytes and 292KB until OOM"
09-13 09:08:32.169 20376-20376/com.bebler.app E/art: Throwing OutOfMemoryError "Failed to allocate a 3879468 byte allocation with 299788 free bytes and 292KB until OOM"
09-13 09:08:33.108 20376-20376/com.bebler.app E/AndroidRuntime: FATAL EXCEPTION: main
                                                                Process: com.bebler.app, PID: 20376
                                                                java.lang.OutOfMemoryError: Failed to allocate a 3879468 byte allocation with 299788 free bytes and 292KB until OOM
                                                                    at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                    at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
                                                                    at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:609)
                                                                    at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:444)
                                                                    at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:988)
                                                                    at android.content.res.Resources.loadDrawableForCookie(Resources.java:2477)
                                                                    at android.content.res.Resources.loadDrawable(Resources.java:2384)
                                                                    at android.content.res.Resources.getDrawable(Resources.java:787)
                                                                    at android.support.v4.content.res.ResourcesCompatApi21.getDrawable(ResourcesCompatApi21.java:31)
                                                                    at android.support.v4.content.res.ResourcesCompat.getDrawable(ResourcesCompat.java:60)
                                                                    at com.bebler.app.activity.fragment.Settings.displayUserData(Settings.java:228)
                                                                    at com.bebler.app.activity.fragment.Settings.onResume(Settings.java:120)
                                                                    at android.support.v4.app.Fragment.performResume(Fragment.java:2238)
                                                                    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1346)
                                                                    at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                    at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:2914)
                                                                    at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:223)
                                                                    at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:509)
                                                                    at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:498)
                                                                    at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:172)
                                                                    at android.app.Activity.performResume(Activity.java:6109)
                                                                    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3011)
                                                                    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3063)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1361)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:135)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

**Comment by NikitaCherep** [comment]
What type of ads you use?

**Comment by legd** [comment]
We are using NativeAd

**Comment by legd** [comment]
hi, is there any update on this matter?

**Comment by legd** [comment]
Hi, is there any news about this? We are stuck in our project waiting for an answer from you, we will appreciate any update.

**Comment by BaxterZA** [comment]
Hi, legd! Sorry for delay. But i don't see our methods in stacktraces. Of course we decode bitmap in native ads and if you want to have more control over this flow, you can disable autocaching images like this:
        Appodeal.setAutoCacheNativeIcons(false);
        Appodeal.setAutoCacheNativeMedia(false);
And use methods getMainImageUrl and getIconUrl instead of getImage and getIcon.

**Comment by legd** [comment]
Hi, BaxterZA thanks for your reply. We implement your suggestions in our app but we still have the OutOfMemoryError, again we check our code and also we made a rollback to the 1.15 Appodeal SDK version and this error did not happen, so again we think your SDK is causing the error, something that I did not mention before is we are targeting the 23 SDK version and our Minimum SDK version is the 17, one more thing we saw in the stack trace was this: 

09-20 14:26:04.721 32684-32684/com.bebler.app E/Base[onNativeFailedToLoad] - 348: ad failed to load
09-20 14:27:34.921 32684-32684/com.bebler.app E/Base[onNativeFailedToLoad] - 348: ad failed to load
09-20 14:31:00.130 32684-32684/com.bebler.app E/Base[onNativeFailedToLoad] - 348: ad failed to load
09-20 14:32:44.785 32684-32684/com.bebler.app E/Base[onNativeFailedToLoad] - 348: ad failed to load

I’m aware that this is our implementation of a method from your interface NativeCallbacks, but my question is, what may be the precise reasons for this method be called? I'm not sure but maybe this will help us to identify the origin of the error.

**Comment by BaxterZA** [comment]
Hi, legd. Can you send both apk for testing? First with OOM error and second with no fill.

**Comment by legd** [comment]
Ok, your email, please.

**Comment by NikitaCherep** [comment]
Hi, legd. When i was testing apk, i did`t see native ads, but a lot of loading this ads show in logs. Maybe this is connected with the fact that you taken all native ads in method onNativeLoaded using getNativeAds. In this case Appodeal will cache native ads again and will callback in the onNativeLoaded and again and again.

09-25 07:06:48.167 28365-29405/com.bebler.app D/dalvikvm: GC_FOR_ALLOC freed 3599K, 22% free 20634K/26384K, paused 11ms, total 12ms
09-25 07:06:48.187 28365-28365/com.bebler.app D/Appodeal: Startapp onNativeLoaded, eCPM: 0.19
09-25 07:06:48.187 28365-28365/com.bebler.app D/Appodeal: onNativeLoaded
09-25 07:06:48.191 28365-28365/com.bebler.app D/Appodeal: Caching Native (debugType: native, isLoaded: true, isLoading: false, size: 4)
09-25 07:06:48.191 28365-28365/com.bebler.app D/Appodeal: getNativeAds: 2
09-25 07:06:48.195 28365-28365/com.bebler.app W/StartAppSDKInternal: FullScreenActivity is missing from AndroidManifest.xml
09-25 07:06:48.739 28365-29697/com.bebler.app D/dalvikvm: GC_FOR_ALLOC freed 3815K, 22% free 20664K/26384K, paused 12ms, total 12ms
09-25 07:06:48.759 28365-28365/com.bebler.app D/Appodeal: Startapp onNativeLoaded, eCPM: 0.19
09-25 07:06:48.759 28365-28365/com.bebler.app D/Appodeal: onNativeLoaded
09-25 07:06:48.759 28365-28365/com.bebler.app D/Appodeal: Caching Native (debugType: native, isLoaded: true, isLoading: false, size: 4)
09-25 07:06:48.759 28365-28365/com.bebler.app D/Appodeal: getNativeAds: 2
09-25 07:06:48.767 28365-28365/com.bebler.app W/StartAppSDKInternal: FullScreenActivity is missing from AndroidManifest.xml
09-25 07:06:49.543 28365-29405/com.bebler.app D/dalvikvm: GC_FOR_ALLOC freed 3694K, 22% free 20636K/26384K, paused 19ms, total 20ms
09-25 07:06:49.563 28365-28365/com.bebler.app D/Appodeal: Startapp onNativeLoaded, eCPM: 0.19
09-25 07:06:49.563 28365-28365/com.bebler.app D/Appodeal: onNativeLoaded
09-25 07:06:49.567 28365-28365/com.bebler.app D/Appodeal: Caching Native (debugType: native, isLoaded: true, isLoading: false, size: 4)
09-25 07:06:49.567 28365-28365/com.bebler.app D/Appodeal: getNativeAds: 2
09-25 07:06:49.571 28365-28365/com.bebler.app W/StartAppSDKInternal: FullScreenActivity is missing from AndroidManifest.xml
09-25 07:06:50.215 28365-29697/com.bebler.app D/dalvikvm: GC_FOR_ALLOC freed 3754K, 22% free 20667K/26384K, paused 9ms, total 10ms
09-25 07:06:50.235 28365-28365/com.bebler.app D/Appodeal: Startapp onNativeLoaded, eCPM: 0.19
09-25 07:06:50.235 28365-28365/com.bebler.app D/Appodeal: onNativeLoaded
09-25 07:06:50.235 28365-28365/com.bebler.app D/Appodeal: Caching Native (debugType: native, isLoaded: true, isLoading: false, size: 4)
09-25 07:06:50.239 28365-28365/com.bebler.app D/Appodeal: getNativeAds: 2
09-25 07:06:50.243 28365-28365/com.bebler.app W/StartAppSDKInternal: FullScreenActivity is missing from AndroidManifest.xml
09-25 07:06:50.591 28365-29855/com.bebler.app W/chromium: [WARNING:simple_index_file.cc(338)] Could not map Simple Index file.
09-25 07:06:50.591 28365-29855/com.bebler.app I/chromium: [INFO:simple_index_file.cc(437)] Simple Cache Index is being restored from disk.
09-25 07:06:50.891 28365-29405/com.bebler.app D/dalvikvm: GC_FOR_ALLOC freed 4401K, 22% free 20712K/26384K, paused 19ms, total 20ms
09-25 07:06:50.931 28365-28365/com.bebler.app D/Appodeal: Startapp onNativeLoaded, eCPM: 0.19
09-25 07:06:50.931 28365-28365/com.bebler.app D/Appodeal: onNativeLoaded
09-25 07:06:50.939 28365-28365/com.bebler.app D/Appodeal: Caching Native (debugType: native, isLoaded: true, isLoading: false, size: 4)
09-25 07:06:50.939 28365-28365/com.bebler.app D/Appodeal: getNativeAds: 2
09-25 07:06:50.951 28365-28365/com.bebler.app W/StartAppSDKInternal: FullScreenActivity is missing from AndroidManifest.xml
09-25 07:06:51.455 28365-29697/com.bebler.app D/dalvikvm: GC_FOR_ALLOC freed 3604K, 22% free 20673K/26384K, paused 10ms, total 16ms
09-25 07:06:51.471 28365-28365/com.bebler.app D/Appodeal: Startapp onNativeLoaded, eCPM: 0.19
09-25 07:06:51.471 28365-28365/com.bebler.app D/Appodeal: onNativeLoaded
09-25 07:06:51.471 28365-28365/com.bebler.app D/Appodeal: Caching Native (debugType: native, isLoaded: true, isLoading: false, size: 4)
09-25 07:06:51.471 28365-28365/com.bebler.app D/Appodeal: getNativeAds: 2
09-25 07:06:51.471 28365-28365/com.bebler.app W/StartAppSDKInternal: FullScreenActivity is missing from AndroidManifest.xml
09-25 07:06:52.199 28365-29405/com.bebler.app D/dalvikvm: GC_FOR_ALLOC freed 3580K, 22% free 20701K/26384K, paused 11ms, total 14ms
09-25 07:06:52.219 28365-28365/com.bebler.app D/Appodeal: Startapp onNativeLoaded, eCPM: 0.19
09-25 07:06:52.219 28365-28365/com.bebler.app D/Appodeal: onNativeLoaded
09-25 07:06:52.219 28365-28365/com.bebler.app D/Appodeal: Caching Native (debugType: native, isLoaded: true, isLoading: false, size: 4)
09-25 07:06:52.219 28365-28365/com.bebler.app D/Appodeal: getNativeAds: 2

**Comment by legd** [comment]
Hi Nikita sorry for not answer sooner, as you said the onNativeLoaded method is called too many times and inside of it we used to call the getNativeAds method, now I’m calling the getNativeAds method with a BroadcastReceiver after the ads are loaded and still I’m having a loop with the onNativeLoaded and getNativeAds, I read in your documentation that the getNativeAds is needed to get the NativeAds objects and it has to be called after the ads are cached, so I don’t understand why this loop is occurring, here is a fragment of how I’m requesting the ads and how I’m getting after they are loaded: 

`new AsyncTask<Void, Void, Void>() {
    @Override
    protected Void doInBackground(Void... params) {

        Appodeal.setNativeCallbacks(new NativeCallbacks() {
            @Override
            public void onNativeLoaded() {
                if (Appodeal.isLoaded(Appodeal.NATIVE)) {
                    Intent adsLoadedIntent = new Intent(ADS_RECEIVER_TAG);
                    LocalBroadcastManager.getInstance(context).sendBroadcast(adsLoadedIntent);
                }
            }

            @Override
            public void onNativeFailedToLoad() {

            }

            @Override
            public void onNativeShown(NativeAd nativeAd) {

            }

            @Override
            public void onNativeClicked(NativeAd nativeAd) {

            }
        });

        Appodeal.initialize(Main.this, api_key, Appodeal.NATIVE);
        Appodeal.setAutoCacheNativeIcons(true);
        Appodeal.setAutoCacheNativeMedia(true);
        Appodeal.cache(Main.this, Appodeal.NATIVE, 10);

        Appodeal.setTesting(BuildConfig.DEBUG); 

        return null;
    }

}.execute();


private BroadcastReceiver mAdsReceiver = new BroadcastReceiver() {
    @Override
    public void onReceive(Context context, Intent intent) {
        List<NativeAd> nativeAds = Appodeal.getNativeAds(10);
        // here I add the ads to a RecyclerAdapter
    }
};`

Keep in mind I will display the native ads as part of a list inside a RecyclerView so I will need ads every n item in the RecyclerView, also eventually I will repeat the process of request and load to get newer ads, so I need a clarification about how this needs to be done.

**Comment by NikitaCherep** [comment]
Hi, legd. You need use getNativeAds and get one ads directly before show ads, for example in adapter. For take status of native ads use Appodeal.isLoaded(Appodeal.NATIVE)

**Comment by legd** [comment]
So, I have to load one ad at a time? can I load a list of 5 or 10 ads at the same time?

**Comment by BaxterZA** [comment]
Hi, legd! I want to clarify loading of native ads . We store loaded native ads inside our container in sdk. First you init native ads with count, after first ad is loaded we fire callback onNativeLoaded. But next, when you call getNativeAds and get all native ads from container (container is empty) we fire callback onNativeLoaded after first ad is loaded. You call getNativeAds  again, and.... And that's why you have endless loading loop.

**Comment by legd** [comment]
Hi sorry for not answering sooner, we implement the SDK as you explained, now our app is working properly, thanks for your support!!

**Comment by BaxterZA** [comment]
You're welcome. I close issue.
