### ISSUE TITLE
MREC is not working

### ISSUE THREAD

**Issue by Firsto** [appodeal/appodeal-android-demo#66]
I saw several times correct MREC ads, but a day ago I got "SDK [Response]: {"status":"error","message":"No ads in MREC"}"

No information in the documentation about this. Someone faced with it? Or MREC is not supported now? (this methods marked as deprecated)

**Comment by da2gl** [comment]
Hi @Firsto.
You can contact our support team through the main dashboard.
They will help with solving your issue. 
Have a nice day.

**Comment by da2gl** [comment]
Hello, @Firsto.
Do you still have questions about how MREC works?

**Comment by Firsto** [comment]
Hooray, is working now! The problem was in incorrect ads identifiers in settings.
